// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int count = Integer.parseInt(args[0]);
		int countBig=0;
		int countSmall=0;
		double random=0;
		for (int i=0; i<=count; i++)
		{
			random = Math.random();
			if (random>0.5) {countBig++;}
			else {countSmall++;}
		}
		System.out.println(">0.5: " + countBig + " times");
		System.out.println("<=0.5 " + countSmall + " times");
		double ratio = 0;
		if (countBig!=0 || countSmall!=0)
		{
			if(countBig>countSmall){ratio = (double) countSmall / countBig;}
			else {ratio = (double) countBig / countSmall;}
			System.out.println("Ratio: " + ratio);
		}
	}
}
